package view.user;

import main.StartFrame;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.User;
import service.UserService;
import view.product.ListProductFrame;

/**
 *
 * @author leanh
 */
public class ListUserFrame extends javax.swing.JFrame {

        UserService userService;
        DefaultTableModel defaultTableModel;

        /**
         * Creates new form ListUserFrame
         *
         * @throws java.sql.SQLException
         */
        public ListUserFrame() throws SQLException {
                initComponents();
                userService = new UserService();

                defaultTableModel = new DefaultTableModel() {
                        @Override
                        public boolean isCellEditable(int row, int column) {
                                return false;
                        }
                };
                userTable.setModel(defaultTableModel);

                defaultTableModel.addColumn("ID");
                defaultTableModel.addColumn("Ten");
                defaultTableModel.addColumn("So DT");
                defaultTableModel.addColumn("Tai khoan");
                defaultTableModel.addColumn("Mat khau");
                defaultTableModel.addColumn("Vai tro");
                defaultTableModel.addColumn("So thich");
                defaultTableModel.addColumn("Gioi thieu");

                setTableData(userService.getAllUsers());
        }

        private void setTableData(List<User> users) {

                for (User user : users) {
                        defaultTableModel.addRow(new Object[]{user.getId(), user.getName(), user.getPhone(), user.getUsername(), user.getPassword(), user.getRole(), user.getFavourites(), user.getAbout()});
                }
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButtonUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        refreshButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        signoutButton = new javax.swing.JButton();
        producttableButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        addButtonUser.setText("ADD");
        addButtonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonUserActionPerformed(evt);
            }
        });

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        userTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        userTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(userTable);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("EDIT");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        signoutButton.setText("Dang Xuat");
        signoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutButtonActionPerformed(evt);
            }
        });

        producttableButton.setText("Product Table");
        producttableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producttableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButtonUser)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)
                        .addGap(18, 18, 18)
                        .addComponent(editButton)
                        .addGap(18, 18, 18)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(producttableButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(signoutButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButtonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(producttableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed

            try {
                    // TODO add your handling code here:
                    defaultTableModel.setRowCount(0);
                    setTableData(userService.getAllUsers());
            } catch (SQLException ex) {
                    Logger.getLogger(ListUserFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void addButtonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonUserActionPerformed
            // TODO add your handling code here:
            new AddUserFrame().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_addButtonUserActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
            // TODO add your handling code here:
            int row = userTable.getSelectedRow();
            if (row == -1) {
                    JOptionPane.showMessageDialog(ListUserFrame.this, "Vui long chon User muon xoa", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                    int confirm = JOptionPane.showConfirmDialog(ListUserFrame.this, "Chac chan muon xoa khong?");

                    if (confirm == JOptionPane.YES_OPTION) {
                            int userId = Integer.valueOf(String.valueOf(userTable.getValueAt(row, 0)));
                            try {
                                    userService.deleteUser(userId);
                                    defaultTableModel.setRowCount(0);
                                    setTableData(userService.getAllUsers());
                            } catch (SQLException ex) {
                                    Logger.getLogger(ListUserFrame.class.getName()).log(Level.SEVERE, null, ex);
                            }
                    }
            }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
            // TODO add your handling code here:
            int row = userTable.getSelectedRow();
            if (row == -1) {
                    JOptionPane.showMessageDialog(ListUserFrame.this, "Vui long chon User muon sua", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                    int userId = Integer.valueOf(String.valueOf(userTable.getValueAt(row, 0)));
                    try {
                            new EditUserFrame(userId).setVisible(true);
                    } catch (SQLException ex) {
                            Logger.getLogger(ListUserFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    this.dispose();
            }
    }//GEN-LAST:event_editButtonActionPerformed

        private void signoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutButtonActionPerformed
                // TODO add your handling code here:
                this.dispose();
                new StartFrame().setVisible(true);
        }//GEN-LAST:event_signoutButtonActionPerformed

        private void producttableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producttableButtonActionPerformed
                // TODO add your handling code here:
                this.dispose();
                try {
                        new ListProductFrame().setVisible(true);
                } catch (SQLException ex) {
                        Logger.getLogger(ListUserFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
        }//GEN-LAST:event_producttableButtonActionPerformed

        /**
         * @param args the command line arguments
         */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButtonUser;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton producttableButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton signoutButton;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
